# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VXUOs7b4ueZhqaRYqtqU0XKwjnQMrLC
"""

# Import necessary libraries
import re


# Define a simple chatbot function
def chatbot():
    print("Hello! I am a simple chatbot. How can I assist you today?")

    while True:
        user_input = input("You: ").strip().lower()  # Take user input and normalize it

        # Exit condition
        if user_input in ["exit", "quit", "bye"]:
            print("Chatbot: Goodbye! Have a great day!")
            break

        # Rule-based responses
        elif re.search(r'hi|hello|hey', user_input):
            print("Chatbot: Hello! How can I help you?")

        elif re.search(r'how are you', user_input):
            print("Chatbot: I'm just a program, but thanks for asking! How can I assist you?")

        elif re.search(r'what is your name', user_input):
            print("Chatbot: I'm a simple chatbot without a name. You can call me Chatbot.")

        elif re.search(r'help|assist', user_input):
            print("Chatbot: Sure! What do you need help with?")

        elif re.search(r'weather', user_input):
            print("Chatbot: I'm unable to provide weather updates right now.")

        elif re.search(r'joke', user_input):
            print("Chatbot: Why did the scarecrow win an award? Because he was outstanding in his field!")

        else:
            print("Chatbot: I'm sorry, I don't understand that. Can you please rephrase?")


# Run the chatbot
if __name__ == "__main__":
    chatbot()